### ISSUE TITLE
Getting error when starting app

### ISSUE THREAD

**Issue by randy-johnson** [EddyVerbruggen/nativescript-mapbox-demo#7]
Hello,

I installed the app, changed out the access token and uncommented out this line in the android manifest:

`<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />`

When I run the app it fires up and I see the first screen.  After a few seconds it then shows this error:

`com.tns.NativeScriptException: 
Calling js method run failed

TypeError: args.map.setViewport is not a function
File: "/data/data/org.nativescript.mapboxdemo/files/app/main-page.js, line: 25, column: 13

StackTrace: 
    Frame: function:'', file:'/data/data/org.nativescript.mapboxdemo/files/app/main-page.js', line: 25, column: 14
    Frame: function:'java.lang.Runnable.run', file:'/data/data/org.nativescript.mapboxdemo/files/app/tns_modules/timer/timer.js', line: 17, column: 13

```
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
at com.tns.Runtime.callJSMethod(Runtime.java:716)
at com.tns.Runtime.callJSMethod(Runtime.java:697)
at com.tns.Runtime.callJSMethod(Runtime.java:687)
at com.tns.gen.java.lang.Runnable.run(java.lang.Runnable.java)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:14`
```

tns --version shows 2.3.0

Any ideas what could be wrong here?

**Comment by EddyVerbruggen** [comment]
The demo expects the mapbox plugin to be 2.2.1 but the package.json of this demo specified "any 2.x version". I've now pinned it to a specific version and you should be good when you pull in [this change](https://github.com/EddyVerbruggen/nativescript-mapbox-demo/commit/0ef0f378f56b0b53e1175e1b6427de016d3b8715).

**Comment by randy-johnson** [comment]
That did the trick.  Thank You for your quick response.
